### ISSUE TITLE
Can't run properly

### ISSUE THREAD

**Issue by dovahkrid** [Rexios80/flutter_m1_patcher#1]
```
Deleting bundled Dart SDK...

Downloading Dart SDK 2.15.0 for macOS arm64...

Unzipping Dart SDK...

Deleting zip file...

Unhandled exception:
FileSystemException: Cannot delete file, path = '/Users/....../Workspace/Flutter/flutter/bin/cache/dart-sdk.zip' (OS Error: No such file or directory, errno = 2)
#0      _File.throwIfError (dart:io/file_impl.dart:635:7)
#1      _File._deleteSync (dart:io/file_impl.dart:298:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:408:7)
#3      main (file:///Users/.../.pub-cache/hosted/pub.dartlang.org/flutter_m1_patcher-1.1.1/bin/flutter_m1_patcher.dart:46:45)
<asynchronous suspension>
```

This is what I got

**Comment by Rexios80** [comment]
One of my coworkers has the same issue. It's weird because it works on both my M1 machines. I think it might have something to do with not having dart installed separately from flutter.

**Comment by Rexios80** [comment]
Yeah that's definitely it. I'm going to try and find a workaround, or worst case update the readme to say you need to install dart from homebrew first.

**Comment by Rexios80** [comment]
I updated the readme to say you need to install dart from homebrew first. Let me know how it goes if you try it again.

**Comment by toby-bdi** [comment]
I've followed the instructions to install dart from homebrew, however when running `dart pub global activate flutter_m1_patcher` I still receive an error with dart versions:

```
The current Dart SDK version is 2.14.4.

Because pub global activate depends on flutter_m1_patcher any which requires SDK version >=2.15.0 <3.0.0, version solving failed.
```

**Comment by Rexios80** [comment]
Is the brew bin folder first in your path? The current dart version is 2.15.1 which is what homebrew would have installed.
